### ISSUE TITLE
Unable to add CP Code to Reporting Group

### ISSUE THREAD

**Issue by cofonseca** [akamai/akamaipowershell#33]
I am trying to use the Set-CPReportingGroup cmdlet to add a CP Code to an existing reporting group. Here's how I'm attempting to do this:

I first get the existing reporting group information by running:
`$Group = Get-CPReportingGroup -ReportingGroupID 123456`

Next, I update the list of CP Codes like this:
`$Group.contracts[0].cpcodes += [pscustomobject]@{cpcodeId=7654321;cpcodeName='test.com.search'}`

Finally, I submit the changes:
`Set-CPReportingGroup -ReportingGroupID 123456 -Body $Group`

This results in a generic 400 error with no additional information:
`The remote server returned an error: (400) Bad Request.`

Unfortunately there isn't any help or other info on how to use these cmdlets, so I'm not sure where to go from here. I've tried other methods of modifying the $Group object but everything I've tried has resulted in a 400. Any ideas or suggestions? Thanks in advance.

**Comment by stuartio** [comment]
Hi @cofonseca,

Sorry for the issue you are having. You are almost there, though. The issue appears to be that the $Body param of the Set-CPReportingGroup is expecting a JSON string, but by sending the PS object the format is off (the module doesn't cast the param to a string, though we could potentially add that).

Try this
`Set-CPReportingGroup -ReportingGroupID 123456 -Body (ConvertTo-Json -depth 100 $Group)`

We have also added support for piping to lots of other APIs, though CPRG hasn't been done yet. I could add it to the list though for the next release.
