### ISSUE TITLE
List-AllProperties does not list property if a group only holds one property

### ISSUE THREAD

**Issue by MarcW64** [akamai/akamaipowershell#34]
If  a group only hold one property, this property is not listed in the output. Reason is that in line 31 the "$PropertiesToAdd.Count" will not be 1 if there is only one property in that list. 
I fixed it for myself with "elseif(($PropertiesToAdd | Measure-Object).Count -eq 1)"

**Comment by stuartio** [comment]
Thanks for that @MarcW64, I will get it fixed asap. Is this in Powershell 5.1 or in 6+? I suspect 6+ will work due to the way it handles single item lists but am curious.

**Comment by MarcW64** [comment]
Thanks for the fast response. On my laptop it's 5.1. So maybe that is the problem. I'm developing for Azure automation so also need to check what is running there. I do not know if we have the issue also in Azure.

**Comment by stuartio** [comment]
OK cool. It is definitely something I can/will fix for PS 5.1, just curious to see if the issue recurs with both. There is a new release pending, but I might be able to sneak this in with it.

**Comment by MarcW64** [comment]
Thanks. Much appreciated.

**Comment by stuartio** [comment]
This should now be working in 1.8.0 @MarcW64. Can you re-test please?

**Comment by MarcW64** [comment]
@stuartio Issue fixed. It works. thanks.
