### ISSUE TITLE
Usage of unapproved verbs

### ISSUE THREAD

**Issue by PrzemyslawKlys** [akamai/akamaipowershell#49]
Hello,

It seems the PowerShell module doesn't follow best practices when it comes to using proper verbs. 

PowerShell provides a list of "approved verbs" that you can find out using:

```powershell
Get-Verb
```

![image](https://github.com/akamai/akamaipowershell/assets/15063294/7a0295cb-2263-4872-bfb0-876c8a3b7128)

Using `List-XXX` is not on the approved list. While technically PowerShell doesn't care it does give warning on importing PowerShell module. 

![image](https://github.com/akamai/akamaipowershell/assets/15063294/de23e442-a963-4902-a4f4-d28302653bc0)

I'm specifically rereferring to:
- https://github.com/akamai/akamaipowershell/blob/master/edgedns/List-RecordSets.ps1
- https://github.com/akamai/akamaipowershell/blob/master/edgedns/List-TSIGKeys.ps1
- https://github.com/akamai/akamaipowershell/blob/master/edgedns/List-Zones.ps1

Usually you would use Get-RecordSets, but I see there's already Get-RecordSet, so you may need to find something else. 

You can find out which commands should be renamed using:

```powershell
Import-Module AkamaiPowershell -Verbose -Force
```

![image](https://github.com/akamai/akamaipowershell/assets/15063294/689ddf63-ecef-49d3-a3d5-fe78f3f12350)

To not introduce breaking changes what you can do is rename the functions, but set aliases for them for people who have automation in place using non-approved verbs.

**Comment by stuartio** [comment]
Hi @PrzemyslawKlys, sorry for the delay in getting back to you. We are finalising the v2 release of the module now, which has all unapproved verbs removed.
