### ISSUE TITLE
Release notes for 1.12.0?

### ISSUE THREAD

**Issue by lukemaslany-next** [akamai/akamaipowershell#51]
Apologies in advance if I'm missing something obvious, but are there any release notes for 0.12.0 of the AkamaiPowershell module?

From what I can see in the PowerShell gallery ([here](https://www.powershellgallery.com/packages/AkamaiPowershell/1.12.0)), 0.12.0 was released three months ago - but the latest release I am seeing in this Github project is 0.11.0?

I'd appreciate it if someone could point me in the right direction.

**Comment by stuartio** [comment]
Hi @lukemaslany-next 

The changelog document gets updated with each release, but I notice it isnt actually linked in the README (we will fix that with the next major release). You can find the updates for 1.12 here

https://github.com/akamai/akamaipowershell/blob/master/CHANGELOG.md

**Comment by lukemaslany-next** [comment]
Much appreciated.  👍
